const actionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  TOGGLE_CART_DROP_DOWN: 'TOGGLE_CART_DROP_DOWN',
  ADD_CART_ITEM: 'ADD_CART_ITEM',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  SUBTRACT_CART_ITEM: 'SUBTRACT_CART_ITEM',
  FETCH_SHOP_DATA_START: 'FETCH_SHOP_DATA_START',
  FETCH_SHOP_DATA_ERROR: 'FETCH_SHOP_DATA_ERROR',
  FETCH_SHOP_DATA_SUCCESS: 'FETCH_SHOP_DATA_SUCCESS',
  SIGNIN_GOOGLE_START: 'SIGNIN_GOOGLE_START',
  SIGNIN_EMAIL_AND_PASSWORD_START: 'SIGNIN_EMAIL_AND_PASSWORD_START',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',
  CHECK_SESSION_USER: 'CHECK_SESSION_USER',
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
  CLEAR_CART: 'CLEAR_CART',
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
}

export {actionTypes}
